[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s - %(levelname)s - %(message)s

markers =
    smoke: Smoke tests
    regression: Regression tests
    login: Login related tests
    windows: Window handling tests
    action: ActionChains tests